[global]
refresh_interval = "60s"
colors = true
emoji = true
notification_cooldown = "5m"

[trusted_hosts]
"github.com" = true
"gitlab.com" = true
"codeberg.org" = true
"bitbucket.org" = true
"sr.ht" = true
